apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kv-to-kube
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, update, create, patch, delete]
- apiGroups: [""]
  resources: [namespaces]
  verbs: [list]
