apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kv-to-kube
subjects:
  - kind: ServiceAccount
    name: kv-to-kube
    namespace: kv-to-kube
roleRef:
  kind: ClusterRole
  name: kv-to-kube
  apiGroup: rbac.authorization.k8s.io
