name: pypi

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build_and_publish_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: |
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - run: poetry build
      - run: poetry publish
